package entity;
// Generated Mar 28, 2018 3:15:10 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Address", catalog = "VoidNet")
public class Address implements java.io.Serializable {

	private int id;
	private Account account;
	private String streetAddress;
	private String zipCode;
	private String state;
	private String country;
	private Set<Order> orders = new HashSet<Order>(0);

	public Address() {
	}

	public Address(int id, Account account, String streetAddress, String zipCode, String state, String country) {
		this.id = id;
		this.account = account;
		this.streetAddress = streetAddress;
		this.zipCode = zipCode;
		this.state = state;
		this.country = country;
	}

	public Address(int id, Account account, String streetAddress, String zipCode, String state, String country,
			Set<Order> orders) {
		this.id = id;
		this.account = account;
		this.streetAddress = streetAddress;
		this.zipCode = zipCode;
		this.state = state;
		this.country = country;
		this.orders = orders;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountLovesId", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "streetAddress", nullable = false, length = 45)
	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	@Column(name = "zipCode", nullable = false, length = 45)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "state", nullable = false, length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
