package entity;
// Generated Mar 28, 2018 3:15:10 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "OrderDetail", catalog = "VoidNet")
public class OrderDetail implements java.io.Serializable {

	private int id;
	private Account account;
	private Order order;
	private Product product;
	private int accountofId;

	public OrderDetail() {
	}

	public OrderDetail(int id, Account account, Order order, Product product, int accountofId) {
		this.id = id;
		this.account = account;
		this.order = order;
		this.product = product;
		this.accountofId = accountofId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderId", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orderId", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productId", nullable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "accountofId", nullable = false)
	public int getAccountofId() {
		return this.accountofId;
	}

	public void setAccountofId(int accountofId) {
		this.accountofId = accountofId;
	}

}